#!/usr/bin/env python3
"""Measure bundled icons and generate their panel margins."""

import argparse
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
STYLESHEET = ROOT / "stylesheet.css"
ICON_LABEL_GAP = 6
START = "/* BEGIN measured icon margins */"
END = "/* END measured icon margins */"


def panel_type(filename):
    name = filename.removesuffix("-symbolic.svg")
    if name == "cpu":
        return "processor"
    if name == "swap":
        return "memory"
    if name == "network-download":
        return "network-rx"
    if name == "network-upload":
        return "network-tx"
    return name


def right_inset(path):
    result = subprocess.run(
        ["magick", "-background", "none", str(path), "-alpha", "extract",
         "-threshold", "0%", "-trim", "-format", "%w %X %[fx:page.width]", "info:"],
        check=True, capture_output=True, text=True,
    )
    width, left, canvas_width = map(int, result.stdout.split())
    return canvas_width - left - width


def measurements():
    icons = []
    insets = {}
    for style in ("gnome", "original"):
        for path in sorted((ROOT / "icons" / style).glob("*-symbolic.svg")):
            inset = right_inset(path)
            key = (style, panel_type(path.name))
            if key in insets and insets[key] != inset:
                raise ValueError(f"Icons in {style}/{key[1]} need separate CSS classes")
            if inset > ICON_LABEL_GAP:
                raise ValueError(f"{path} needs a gap above {inset}px")
            insets[key] = inset
            icons.append((style, path.name, inset))
    return icons, insets


def write_css(insets):
    css = STYLESHEET.read_text()
    if css.count(START) != 1 or css.count(END) != 1:
        raise ValueError("Expected one measured icon margin block in stylesheet.css")

    rules = [f"/* Generated by tools/icon-spacing.py; visible gap: {ICON_LABEL_GAP}px. */"]
    for (style, sensor_type), inset in insets.items():
        rules.append(
            f".vitals-panel-icon-{style}.vitals-panel-icon-{sensor_type} "
            f"{{ margin-right: {ICON_LABEL_GAP - inset}px; }} /* right inset: {inset}px */"
        )

    css = re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        START + "\n" + "\n".join(rules) + "\n" + END,
        css,
        flags=re.DOTALL,
    )
    STYLESHEET.write_text(css)


def css_margin(css, style, sensor_type):
    rule = re.search(
        rf"\.vitals-panel-icon-{style}\.vitals-panel-icon-{sensor_type}"
        r"\s*\{\s*margin-right:\s*(\d+)px;\s*\}",
        css,
    )
    if not rule:
        raise ValueError(f"Missing CSS margin for {style}/{sensor_type}")
    return int(rule[1])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-css", action="store_true", help="update the generated CSS block")
    args = parser.parse_args()

    icons, insets = measurements()
    if args.write_css:
        write_css(insets)

    css = STYLESHEET.read_text()
    print(f"Visible icon-to-label gap: {ICON_LABEL_GAP}px")
    print(f"{'Style':8} {'Icon':29} {'Inset':>5} {'CSS':>5} {'Gap':>5}")
    for style, filename, inset in icons:
        margin = css_margin(css, style, panel_type(filename))
        print(f"{style:8} {filename:29} {inset:5} {margin:5} {inset + margin:5}")


if __name__ == "__main__":
    main()
